### ISSUE TITLE
Show timestamp on asked questions

### ISSUE THREAD

**Issue by kongr45gpen** [kongr45gpen/indiqa#13]
Questions shown on the interface do not have currently any timestamp associated with them. This makes it hard to pinpoint when a question was asked, and which part of any running presentation it is referring to.

A small timestamp in the local timezone should be added for each question that is displayed:
- On the Main view
- On the Admin view

### Example Design
![image](https://user-images.githubusercontent.com/720678/140054938-e9de81cd-c15b-4901-b742-4266efbfe976.png)

**Comment by Florentin-bron** [comment]
Hello I would be interested about helping you on this issue can you provide me more details about it ?

**Comment by kongr45gpen** [comment]
> 
> 
> Hello I would be interested about helping you on this issue can you provide me more details about it ?

Sure! I have updated the issue's description with a few more details.

PS: I haven't gotten around to updating the README to include installation information yet, but this is a [Meteor app](https://react-tutorial.meteor.com/) so you can follow any tutorials for it.
